name: Coverage Badge for README
on:
  pull_request:
    types:
      - closed
jobs:
  Update-Coverage-on-README:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: ./coverage.svg

      - name: Build coverage file and svg
        run: |
          coverage run -m unittest discover
          coverage-badge -o coverage.svg
      # - name: Pytest coverage comment
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   id: coverageComment
      #   uses: MishaKav/pytest-coverage-comment@main
      #   with:
      #     hide-comment: true
      #     pytest-coverage-path: pytest-coverage.txt
      #     junitxml-path: pytest_cov.xml
      #     badge-title: Coverage

      # - name: Create Variable of Summary Report
      #   id: summary_report
      #   run: |
      #     SUMMARY_REPORT=${{ steps.coverageComment.outputs.summaryReport }}
      #     echo "::set-output name=content::$SUMMARY_REPORT"
      
      # - name: Create the Badge
      #   uses: schneegans/dynamic-badges-action@v1.0.0
      #   with:
      #     auth: ${{ secrets.GIST_SECRET }}
      #     gistID: fa30c0cc061747ad9bfd1cebc9f946e8
      #     filename: pytest-coverage-comment__main.json
      #     label: Coverage
      #     message: ${{ steps.coverageComment.outputs.coverage }}
      #     color: ${{ steps.coverageComment.outputs.color }}
      
      

      - name: Commit & Push changes to Readme
        #if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions-js/push@master
        with:
          message: Update coverage on Readme
          github_token: ${{ secrets.REPO_TOKEN }}
      
      
